version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - TEAM_DATA_LOCATION=/usr/src/app
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./player_teams.json:/usr/src/app/player_teams.json
